# Coherency - Data Echelon Only
# This file launches only the required data services: PostgreSQL.

services:
  # PostgreSQL Database
  postgres:
    container_name: coherency-postgres
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=coherency
      - POSTGRES_USER=coherency
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/database/init.sql:/docker-entrypoint-initdb.d/init.sql

# Declare the named volumes for data persistence
volumes:
  postgres_data: