name: canopy
description: "The official mobile application for the Coherency Health Platform."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

# The version of your application. A "flutter build" command uses this.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# =============================================================
# ==                  APPLICATION DEPENDENCIES               ==
# =============================================================
dependencies:
  flutter:
    sdk: flutter

  # --- State Management ---
  # The core of our state management strategy using the BLoC pattern.
  flutter_bloc: ^8.1.3

  # --- Networking ---
  # A powerful and reliable HTTP client for all API communications.
  dio: ^5.3.3
  
  # --- Dependency Injection / Service Location ---
  # A simple service locator for decoupling our app's layers and locating BLoCs/Repositories.
  get_it: ^7.6.4
  
  # --- Navigation ---
  # Declarative, URL-based routing perfect for complex apps with deep linking.
  go_router: ^12.1.1

  # --- Functional Programming & Utilities ---
  # Provides value equality without boilerplate, essential for BLoC states/events.
  equatable: ^2.0.5
  # Functional programming constructs, mainly for Either<Failure, Success> error handling.
  dartz: ^0.10.1 
  
  # --- Secure Storage ---
  # For securely persisting sensitive data like authentication tokens.
  flutter_secure_storage: ^9.0.0

  # --- Environment Variable Management ---
  # For managing different configurations (dev, staging, prod) via .env files.
  flutter_dotenv: ^5.1.0

# =============================================================
# ==                   DEVELOPMENT DEPENDENCIES              ==
# =============================================================
dev_dependencies:
  flutter_test:
    sdk: flutter

  # --- Code Generation & Linting ---
  # A tool to run code generators, essential if we use things like Freezed or Retrofit later.
  build_runner: ^2.4.6
  # The recommended set of linting rules to keep the code clean and consistent.
  flutter_lints: ^3.0.0


# =============================================================
# ==                     FLUTTER CONFIGURATION               ==
# =============================================================
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material.Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # We will add assets like images and .env files here later.
  # assets:
  #   - .env
  #   - assets/images/logo.png

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. For details, see
  # https://flutter.dev/custom-fonts/#from-packages