name: canopy
description: "The official mobile application for the Coherency Health Platform."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

# The version of your application. A "flutter build" command uses this.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# =============================================================
# ==                  APPLICATION DEPENDENCIES               ==
# =============================================================
dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3

  dio: ^5.3.3
  
  # --- Dependency Injection / Service Location ---
  # A simple service locator for decoupling our app's layers and locating BLoCs/Repositories.
  get_it: ^7.6.4
  
  go_router: ^12.1.1

  equatable: ^2.0.5
  dartz: ^0.10.1 
  
  flutter_secure_storage: ^9.0.0

  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  http: ^1.1.0
  shared_preferences: ^2.2.2

  

# =============================================================
# ==                   DEVELOPMENT DEPENDENCIES              ==
# =============================================================
dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: "^0.14.1"

  


# pubspec.yaml

# =============================================================
# ==                     FLUTTER CONFIGURATION               ==
# =============================================================
flutter:
  uses-material-design: true
  assets:
    - assets/images/


# --- CONFIGURATION FOR NATIVE SPLASH SCREEN (FIXES FITTING) ---
flutter_native_splash:
  # This property stretches the image to fill the entire screen, giving the
  # "end-to-end" look you want.
  # IMPORTANT: Make sure 'Coherency.png' is designed as a background image.
  background_image: "assets/images/Coherency.png"

  # We use a solid color as a fallback in case the image can't load.
  color: "#121212"


# --- CONFIGURATION FOR APP LAUNCHER ICON (FIXES CIRCLE ZOOM) ---
flutter_launcher_icons:
  android: true
  ios: true

  # The main image path used for iOS and legacy Android.
  image_path: "assets/images/app_logo.png"

  # --- This is the key for modern Android icons ---
  # This tells the generator what color to use as the icon background.
  adaptive_icon_background: "#121212"

  # This tells the generator to use your image as the foreground layer.
  # It will be "zoomed" to fit properly on top of the background color.
  adaptive_icon_foreground: "assets/images/app_logo.png"

